import { Karla } from "next/font/google";
import "./globals.css";

import HeaderContainer from "./(public)/ui/HeaderContainer";

const karla = Karla({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={karla.className}>
        <section className="p-2 flex justify-between bg-gray-50 shadow-sm md:h-[5vh]">
          <HeaderContainer reload={new Date.now()} />
        </section>
        <section className="w-full h-[95vh]">{children}</section>
      </body>
    </html>
  );
}
