import { Karla } from "next/font/google";
import "../globals.css";
import Header from "./ui/Header";

const karla = Karla({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <html lang="en">
      <body className={karla.className}>
        <section className="p-2 flex justify-between bg-gray-50 shadow-sm md:h-[5vh]">
          <Header />
        </section>
        <section className="md:h-[95vh] ">{children}</section>
      </body>
    </html>
  );
}
