export const researchers = [
  {
    id: 11,
    name: { firstname: "John", othername: "", surname: "Doe" },
    email: "john.doe@example.com",
    sex: "Male",
    currentLevel: "PhD",
    position: "Lecturer",
    faculty: "Science",
    department: "Biology",
    university: "University of Nairobi",
    ORCIDNumber: "0000-0001-2345-6789",
    googleScholarProfile: "https://scholar.google.com/citations?user=abc123",
    researchGateProfile: "https://www.researchgate.net/profile/John-Doe",
    shortBio: "John Doe specializes in molecular biology and genetics.",
    areaOfSpecialization: ["Molecular Biology", "Genetics"],
    researchInterest: ["Gene Therapy", "CRISPR Technology"],
    cohort: "2023",
    PhDResearchTitle: "Exploring Genetic Mutations in Disease Resistance",
    CARTAGraduate: true,
  },
  {
    id: 22,
    name: { firstname: "Jane", othername: "", surname: "Smith" },
    email: "jane.smith@example.com",
    sex: "Female",
    currentLevel: "PhD",
    position: "Research Assistant",
    faculty: "Engineering",
    department: "Computer Science",
    university: "Makerere University",
    ORCIDNumber: "0000-0002-3456-7890",
    googleScholarProfile: "https://scholar.google.com/citations?user=def456",
    researchGateProfile: "https://www.researchgate.net/profile/Jane-Smith",
    shortBio: "Jane Smith is a data scientist working on AI for healthcare.",
    areaOfSpecialization: ["Artificial Intelligence", "Machine Learning"],
    researchInterest: ["Healthcare AI", "NLP"],
    cohort: "2022",
    PhDResearchTitle: "AI Models for Early Disease Detection",
    CARTAGraduate: false,
  },
  {
    id: 33,
    name: { firstname: "Alice", othername: "", surname: "Johnson" },
    email: "alice.johnson@example.com",
    sex: "Female",
    currentLevel: "PhD",
    position: "Senior Lecturer",
    faculty: "Social Sciences",
    department: "Psychology",
    university: "University of Ghana",
    ORCIDNumber: "0000-0003-5678-1234",
    googleScholarProfile: "https://scholar.google.com/citations?user=ghi789",
    researchGateProfile: "https://www.researchgate.net/profile/Alice-Johnson",
    shortBio: "Alice Johnson researches cognitive behavior in education.",
    areaOfSpecialization: ["Educational Psychology", "Cognitive Science"],
    researchInterest: ["Learning Disabilities", "Behavioral Patterns"],
    cohort: "2020",
    PhDResearchTitle: "Cognitive Patterns in Modern Education Systems",
    CARTAGraduate: true,
  },
  {
    id: 44,
    name: { firstname: "Bob", othername: "", surname: "Williams" },
    email: "bob.williams@example.com",
    sex: "Male",
    currentLevel: "PhD",
    position: "Researcher",
    faculty: "Engineering",
    department: "Mechanical Engineering",
    university: "University of Cape Town",
    ORCIDNumber: "0000-0004-6789-1234",
    googleScholarProfile: "https://scholar.google.com/citations?user=xyz101",
    researchGateProfile: "https://www.researchgate.net/profile/Bob-Williams",
    shortBio: "Bob Williams focuses on sustainable energy and engineering.",
    areaOfSpecialization: ["Mechanical Engineering", "Renewable Energy"],
    researchInterest: ["Solar Energy", "Wind Turbines"],
    cohort: "2012",
    PhDResearchTitle: "Development of Sustainable Energy Solutions",
    CARTAGraduate: false,
  },
  {
    id: 53,
    name: { firstname: "Eve", othername: "", surname: "Martinez" },
    email: "eve.martinez@example.com",
    sex: "Female",
    currentLevel: "PhD",
    position: "Research Fellow",
    faculty: "Humanities",
    department: "History",
    university: "University of Ibadan",
    ORCIDNumber: "0000-0005-7890-1234",
    googleScholarProfile: "https://scholar.google.com/citations?user=lmn123",
    researchGateProfile: "https://www.researchgate.net/profile/Eve-Martinez",
    shortBio:
      "Eve Martinez specializes in African history and cultural studies.",
    areaOfSpecialization: ["History", "Cultural Studies"],
    researchInterest: ["Post-Colonial Studies", "African Identity"],
    cohort: "2021",
    phdResearchTitle: "Post-Colonial Narratives in African Literature",
    CARTAGraduate: true,
  },
  {
    id: 63,
    name: { firstname: "Oliver", othername: "", surname: "Thomas" },
    email: "oliver.thomas@example.com",
    sex: "Male",
    currentLevel: "PhD",
    position: "Assistant Professor",
    faculty: "Science",
    department: "Chemistry",
    university: "University of Dar es Salaam",
    ORCIDNumber: "0000-0006-8901-2345",
    googleScholarProfile: "https://scholar.google.com/citations?user=pqr456",
    researchGateProfile: "https://www.researchgate.net/profile/Oliver-Thomas",
    shortBio: "Oliver Thomas works in chemical engineering and nanotechnology.",
    areaOfSpecialization: ["Chemistry", "Nanotechnology"],
    researchInterest: ["Nano Materials", "Energy Storage"],
    cohort: "2024",
    phdResearchTitle: "Nanomaterials for Energy Applications",
    CARTAGraduate: false,
  },
  {
    id: 73,
    name: { firstname: "Sophia", othername: "", surname: "Clark" },
    email: "sophia.clark@example.com",
    sex: "Female",
    currentLevel: "PhD",
    position: "Postdoctoral Fellow",
    faculty: "Engineering",
    department: "Electrical Engineering",
    university: "Addis Ababa University",
    ORCIDNumber: "0000-0007-9012-3456",
    googleScholarProfile: "https://scholar.google.com/citations?user=stu789",
    researchGateProfile: "https://www.researchgate.net/profile/Sophia-Clark",
    shortBio: "Sophia Clark investigates energy-efficient electrical systems.",
    areaOfSpecialization: ["Electrical Engineering", "Power Systems"],
    researchInterest: ["Smart Grids", "Energy Efficiency"],
    cohort: 7,
    phdResearchTitle: "Optimizing Power Distribution for Sustainability",
    CARTAGraduate: true,
  },
  {
    id: 83,
    name: { firstname: "Jack", othername: "", surname: "Davies" },
    email: "jack.davies@example.com",
    sex: "Male",
    currentLevel: "PhD",
    position: "Lecturer",
    faculty: "Engineering",
    department: "Civil Engineering",
    university: "Stellenbosch University",
    ORCIDNumber: "0000-0008-1234-5678",
    googleScholarProfile: "https://scholar.google.com/citations?user=uvw012",
    researchGateProfile: "https://www.researchgate.net/profile/Jack-Davies",
    shortBio: "Jack Davies researches sustainable construction and materials.",
    areaOfSpecialization: ["Civil Engineering", "Construction Management"],
    researchInterest: ["Green Building", "Eco-Friendly Materials"],
    cohort: 8,
    phdResearchTitle: "Sustainable Construction Materials for Future Cities",
    CARTAGraduate: false,
  },
  {
    id: 93,
    name: { firstname: "Liam", othername: "", surname: "Miller" },
    email: "liam.miller@example.com",
    sex: "Male",
    currentLevel: "PhD",
    position: "Researcher",
    faculty: "Health Sciences",
    department: "Medicine",
    university: "University of Zambia",
    ORCIDNumber: "0000-0009-2345-6789",
    googleScholarProfile: "https://scholar.google.com/citations?user=wxy345",
    researchGateProfile: "https://www.researchgate.net/profile/Liam-Miller",
    shortBio: "Liam Miller focuses on public health and epidemiology.",
    areaOfSpecialization: ["Public Health", "Epidemiology"],
    researchInterest: ["Disease Prevention", "Global Health"],
    cohort: 9,
    phdResearchTitle: "Health Intervention Strategies for Rural Populations",
    CARTAGraduate: true,
  },
  {
    id: 103,
    name: { firstname: "Olivia", othername: "", surname: "Taylor" },
    email: "olivia.taylor@example.com",
    sex: "Female",
    currentLevel: "PhD",
    position: "Senior Researcher",
    faculty: "Arts",
    department: "Linguistics",
    university: "University of Pretoria",
    ORCIDNumber: "0000-0010-3456-7890",
    googleScholarProfile: "https://scholar.google.com/citations?user=abc234",
    researchGateProfile: "https://www.researchgate.net/profile/Olivia-Taylor",
    shortBio:
      "Olivia Taylor specializes in language development and sociolinguistics.",
    areaOfSpecialization: ["Linguistics", "Sociolinguistics"],
    researchInterest: ["Language Acquisition", "Sociolinguistic Variation"],
    cohort: 10,
    PhDResearchTitle: "Language Development in Multi-Lingual Contexts",
    CARTAGraduate: false,
  },
  {
    id: 1,
    name: { firstname: "Alice", othername: "", surname: "Johnson" },
    email: "alice.johnson@example.com",
    sex: "Female",
    currentLevel: "PhD Candidate",
    position: "Research Assistant",
    faculty: "Science",
    department: "Biology",
    university: "University of Oxford",
    ORCIDNumber: "0000-0001-2345-6789",
    googleScholarProfile: "https://scholar.google.com/alicejohnson",
    researchGateProfile: "https://www.researchgate.net/profile/Alice_Johnson",
    shortBio:
      "Alice is a passionate biologist specializing in molecular genetics.",
    areaOfSpecialization: ["Molecular Genetics", "Genomics"],
    researchInterest: ["Gene editing", "Epigenetics", "CRISPR technology"],
    cohort: "2023",
    PhDResearchTitle: "Epigenetic Modifications in Plant Genomes",
    CARTAGraduate: true,
  },
  {
    id: 2,
    name: { firstname: "Bob", othername: "", surname: "Smith" },
    email: "bob.smith@example.com",
    sex: "Male",
    currentLevel: "Postdoctoral Fellow",
    position: "Lecturer",
    faculty: "Engineering",
    department: "Mechanical Engineering",
    university: "MIT",
    ORCIDNumber: "http0000-0002-3456-7890",
    googleScholarProfile: "https://scholar.google.com/bobsmith",
    researchGateProfile: "https://www.researchgate.net/profile/Bob_Smith",
    shortBio:
      "Bob is an expert in fluid mechanics with a focus on renewable energy.",
    areaOfSpecialization: ["Fluid Mechanics", "Renewable Energy Systems"],
    researchInterest: [
      "Wind energy",
      "Hydraulic turbines",
      "Energy efficiency",
    ],
    cohort: "2021",
    PhDResearchTitle: "Optimization of Hydraulic Turbines for Renewable Energy",
    CARTAGraduate: false,
  },
  {
    id: 3,
    name: { firstname: "Catherine", othername: "", surname: "Lee" },
    email: "catherine.lee@example.com",
    sex: "Female",
    currentLevel: "PhD Graduate",
    position: "Senior Scientist",
    faculty: "Medicine",
    department: "Immunology",
    university: "Harvard University",
    ORCIDNumber: "0000-0003-4567-8901",
    googleScholarProfile: "https://scholar.google.com/catherinelee",
    researchGateProfile: "https://www.researchgate.net/profile/Catherine_Lee",
    shortBio:
      "Catherine is a renowned immunologist exploring immune responses to pathogens.",
    areaOfSpecialization: ["Immunology", "Pathogen-Host Interactions"],
    researchInterest: [
      "Vaccine development",
      "Autoimmune diseases",
      "T-cell biology",
    ],
    cohort: "2020",
    PhDResearchTitle: "Mechanisms of T-Cell Activation in Viral Infections",
    CARTAGraduate: true,
  },
  {
    id: 4,
    name: { firstname: "Daniel", othername: "", surname: "Martinez" },
    email: "daniel.martinez@example.com",
    sex: "Male",
    currentLevel: "PhD Candidate",
    position: "Teaching Assistant",
    faculty: "Social Sciences",
    department: "Psychology",
    university: "Stanford University",
    ORCIDNumber: "0000-0004-5678-9012",
    googleScholarProfile: "https://scholar.google.com/danielmartinez",
    researchGateProfile: "https://www.researchgate.net/profile/Daniel_Martinez",
    shortBio:
      "Daniel focuses on cognitive development and mental health research.",
    areaOfSpecialization: ["Cognitive Psychology", "Neuroscience"],
    researchInterest: [
      "Memory",
      "Child development",
      "Mental health interventions",
    ],
    cohort: "2022",
    PhDResearchTitle:
      "The Impact of Early Childhood Experiences on Cognitive Growth",
    CARTAGraduate: false,
  },
  {
    id: 5,
    name: { firstname: "Emily", othername: "", surname: "Nguyen" },
    email: "emily.nguyen@example.com",
    sex: "Female",
    currentLevel: "PhD Graduate",
    position: "Adjunct Professor",
    faculty: "Law",
    department: "International Law",
    university: "University of Toronto",
    ORCIDNumber: "0000-0005-6789-0123",
    googleScholarProfile: "https://scholar.google.com/emilynguyen",
    researchGateProfile: "https://www.researchgate.net/profile/Emily_Nguyen",
    shortBio:
      "Emily specializes in international human rights and legal frameworks.",
    areaOfSpecialization: ["International Law", "Human Rights"],
    researchInterest: ["Global justice", "Refugee rights", "Environmental law"],
    cohort: "2019",
    PhDResearchTitle: "Reforming International Legal Systems for Human Rights",
    CARTAGraduate: true,
  },
  {
    id: 6,
    name: { firstname: "Frank", othername: "", surname: "O'Connor" },
    email: "frank.oconnor@example.com",
    sex: "Male",
    currentLevel: "PhD Candidate",
    position: "Research Fellow",
    faculty: "Arts",
    department: "History",
    university: "Yale University",
    ORCIDNumber: "0000-0006-7890-1234",
    googleScholarProfile: "https://scholar.google.com/frankoconnor",
    researchGateProfile: "https://www.researchgate.net/profile/Frank_OConnor",
    shortBio:
      "Frank is dedicated to exploring medieval European history and cultural dynamics.",
    areaOfSpecialization: ["Medieval History", "Cultural Studies"],
    researchInterest: [
      "Feudal systems",
      "Medieval literature",
      "Cultural exchanges",
    ],
    cohort: "2024",
    PhDResearchTitle: "Cultural Dynamics of Feudal Europe",
    CARTAGraduate: false,
  },
  {
    id: 7,
    name: { firstname: "Grace", othername: "", surname: "Kim" },
    email: "grace.kim@example.com",
    sex: "Female",
    currentLevel: "Postdoctoral Fellow",
    position: "Assistant Professor",
    faculty: "Engineering",
    department: "Electrical Engineering",
    university: "Caltech",
    ORCIDNumber: "0000-0007-8901-2345",
    googleScholarProfile: "https://scholar.google.com/gracekim",
    researchGateProfile: "https://www.researchgate.net/profile/Grace_Kim",
    shortBio:
      "Grace researches renewable energy systems and sustainable electrical engineering solutions.",
    areaOfSpecialization: ["Renewable Energy", "Sustainable Engineering"],
    researchInterest: [
      "Solar power optimization",
      "Energy storage",
      "Smart grids",
    ],
    cohort: "2020",
    PhDResearchTitle:
      "Optimization of Solar Power Systems for Urban Environments",
    CARTAGraduate: true,
  },
  {
    id: 8,
    name: { firstname: "Henry", othername: "", surname: "Zhang" },
    email: "henry.zhang@example.com",
    sex: "Male",
    currentLevel: "PhD Graduate",
    position: "Senior Researcher",
    faculty: "Science",
    department: "Chemistry",
    university: "University of Cambridge",
    ORCIDNumber: "0000-0008-9012-3456",
    googleScholarProfile: "https://scholar.google.com/henryzhang",
    researchGateProfile: "https://www.researchgate.net/profile/Henry_Zhang",
    shortBio:
      "Henry specializes in organic chemistry with a focus on sustainable chemical processes.",
    areaOfSpecialization: ["Organic Chemistry", "Sustainable Processes"],
    researchInterest: [
      "Catalysis",
      "Green chemistry",
      "Biodegradable materials",
    ],
    cohort: "2018",
    PhDResearchTitle:
      "Development of Sustainable Catalysts for Organic Synthesis",
    CARTAGraduate: true,
  },
  {
    id: 9,
    name: { firstname: "Isabella", othername: "", surname: "Garcia" },
    email: "isabella.garcia@example.com",
    sex: "Female",
    currentLevel: "PhD Candidate",
    position: "Teaching Assistant",
    faculty: "Medicine",
    department: "Neuroscience",
    university: "Johns Hopkins University",
    ORCIDNumber: "0000-0009-0123-4567",
    googleScholarProfile: "https://scholar.google.com/isabellagarcia",
    researchGateProfile: "https://www.researchgate.net/profile/Isabella_Garcia",
    shortBio:
      "Isabella is investigating neural pathways involved in cognitive disorders.",
    areaOfSpecialization: ["Neuroscience", "Cognitive Disorders"],
    researchInterest: [
      "Neuroplasticity",
      "Alzheimer's research",
      "Brain-computer interfaces",
    ],
    cohort: "2023",
    PhDResearchTitle: "Neuroplasticity in Early-Stage Alzheimer's Disease",
    CARTAGraduate: false,
  },
  {
    id: 10,
    name: { firstname: "Jack", othername: "", surname: "Brown" },
    email: "jack.brown@example.com",
    sex: "Male",
    currentLevel: "Postdoctoral Fellow",
    position: "Research Scientist",
    faculty: "Science",
    department: "Physics",
    university: "Princeton University",
    ORCIDNumber: "0000-0010-1234-5678",
    googleScholarProfile: "https://scholar.google.com/jackbrown",
    researchGateProfile: "https://www.researchgate.net/profile/Jack_Brown",
    shortBio:
      "Jack's research focuses on quantum mechanics and its applications in computing.",
    areaOfSpecialization: ["Quantum Mechanics", "Quantum Computing"],
    researchInterest: [
      "Quantum algorithms",
      "Entanglement",
      "Superconducting qubits",
    ],
    cohort: "2019",
    PhDResearchTitle: "Developing Quantum Algorithms for Efficient Computation",
    CARTAGraduate: true,
  },
  {
    id: 11,
    name: { firstname: "Karen", othername: "", surname: "Davis" },
    email: "karen.davis@example.com",
    sex: "Female",
    currentLevel: "PhD Graduate",
    position: "Associate Professor",
    faculty: "Business",
    department: "Marketing",
    university: "University of Chicago",
    ORCIDNumber: "0000-0011-2345-6789",
    googleScholarProfile: "https://scholar.google.com/karendavis",
    researchGateProfile: "https://www.researchgate.net/profile/Karen_Davis",
    shortBio:
      "Karen specializes in consumer behavior and digital marketing strategies.",
    areaOfSpecialization: ["Consumer Behavior", "Digital Marketing"],
    researchInterest: [
      "Social media marketing",
      "Brand loyalty",
      "E-commerce trends",
    ],
    cohort: "2017",
    PhDResearchTitle: "Impact of Social Media on Brand Loyalty in E-commerce",
    CARTAGraduate: true,
  },
  {
    id: 12,
    name: { firstname: "Liam", othername: "", surname: "Wilson" },
    email: "liam.wilson@example.com",
    sex: "Male",
    currentLevel: "PhD Candidate",
    position: "Research Assistant",
    faculty: "Engineering",
    department: "Civil Engineering",
    university: "Georgia Institute of Technology",
    ORCIDNumber: "0000-0012-3456-7890",
    googleScholarProfile: "https://scholar.google.com/liamwilson",
    researchGateProfile: "https://www.researchgate.net/profile/Liam_Wilson",
    shortBio:
      "Liam is working on sustainable infrastructure and resilient urban design.",
    areaOfSpecialization: ["Sustainable Infrastructure", "Urban Resilience"],
    researchInterest: [
      "Green building materials",
      "Urban planning",
      "Disaster mitigation",
    ],
    cohort: "2024",
    PhDResearchTitle:
      "Developing Resilient Urban Infrastructure for Sustainable Cities",
    CARTAGraduate: false,
  },
  {
    id: 13,
    name: { firstname: "Mia", othername: "", surname: "Taylor" },
    email: "mia.taylor@example.com",
    sex: "Female",
    currentLevel: "Postdoctoral Fellow",
    position: "Senior Researcher",
    faculty: "Science",
    department: "Environmental Science",
    university: "University of California, Berkeley",
    ORCIDNumber: "0000-0013-4567-8901",
    googleScholarProfile: "https://scholar.google.com/miataylor",
    researchGateProfile: "https://www.researchgate.net/profile/Mia_Taylor",
    shortBio:
      "Mia focuses on climate change impacts and sustainable ecosystem management.",
    areaOfSpecialization: ["Climate Science", "Ecosystem Management"],
    researchInterest: [
      "Carbon sequestration",
      "Biodiversity",
      "Climate resilience",
    ],
    cohort: "2020",
    PhDResearchTitle:
      "Assessing Carbon Sequestration Potential in Urban Ecosystems",
    CARTAGraduate: true,
  },
  {
    id: 14,
    name: { firstname: "Noah", othername: "", surname: "Anderson" },
    email: "noah.anderson@example.com",
    sex: "Male",
    currentLevel: "PhD Graduate",
    position: "Lecturer",
    faculty: "Humanities",
    department: "Philosophy",
    university: "Columbia University",
    ORCIDNumber: "0000-0014-5678-9012",
    googleScholarProfile: "https://scholar.google.com/noahanderson",
    researchGateProfile: "https://www.researchgate.net/profile/Noah_Anderson",
    shortBio:
      "Noah explores ethical theories and their applications in modern society.",
    areaOfSpecialization: ["Ethics", "Applied Philosophy"],
    researchInterest: ["Bioethics", "Moral philosophy", "Political ethics"],
    cohort: "2016",
    PhDResearchTitle:
      "Ethical Implications of Artificial Intelligence in Society",
    CARTAGraduate: true,
  },
  {
    id: 15,
    name: { firstname: "Olivia", othername: "", surname: "Hernandez" },
    email: "olivia.hernandez@example.com",
    sex: "Female",
    currentLevel: "PhD Candidate",
    position: "Research Assistant",
    faculty: "Science",
    department: "Astronomy",
    university: "California Institute of Technology",
    ORCIDNumber: "0000-0015-6789-0123",
    googleScholarProfile: "https://scholar.google.com/oliviahernandez",
    researchGateProfile:
      "https://www.researchgate.net/profile/Olivia_Hernandez",
    shortBio:
      "Olivia is dedicated to studying exoplanets and their potential for hosting life.",
    areaOfSpecialization: ["Exoplanetary Science", "Astrobiology"],
    researchInterest: [
      "Planetary atmospheres",
      "Habitability criteria",
      "Astrobiological signatures",
    ],
    cohort: "2025",
    PhDResearchTitle:
      "Characterizing Atmospheric Conditions of Potentially Habitable Exoplanets",
    CARTAGraduate: false,
  },
  {
    id: 16,
    name: { firstname: "Paul", othername: "", surname: "Garcia" },
    email: "paul.garcia@example.com",
    sex: "Male",
    currentLevel: "Postdoctoral Fellow",
    position: "Research Scientist",
    faculty: "Medicine",
    department: "Public Health",
    university: "University of Washington",
    ORCIDNumber: "0000-0016-7890-1234",
    googleScholarProfile: "https://scholar.google.com/paulgarcia",
    researchGateProfile: "https://www.researchgate.net/profile/Paul_Garcia",
    shortBio:
      "Paul's work focuses on epidemiology and the social determinants of health.",
    areaOfSpecialization: ["Epidemiology", "Public Health"],
    researchInterest: [
      "Infectious diseases",
      "Health disparities",
      "Preventive medicine",
    ],
    cohort: "2019",
    PhDResearchTitle:
      "Impact of Socioeconomic Factors on the Spread of Infectious Diseases",
    CARTAGraduate: true,
  },
  {
    id: 17,
    name: { firstname: "Quincy", othername: "", surname: "Robinson" },
    email: "quincy.robinson@example.com",
    sex: "Male",
    currentLevel: "PhD Graduate",
    position: "Associate Professor",
    faculty: "Computer Science",
    department: "Artificial Intelligence",
    university: "Carnegie Mellon University",
    ORCIDNumber: "0000-0017-8901-2345",
    googleScholarProfile: "https://scholar.google.com/quincrobinson",
    researchGateProfile: "https://www.researchgate.net/profile/Quincy_Robinson",
    shortBio:
      "Quincy specializes in machine learning algorithms and their applications in healthcare.",
    areaOfSpecialization: ["Machine Learning", "Healthcare Informatics"],
    researchInterest: [
      "Predictive analytics",
      "Medical imaging",
      "Natural language processing",
    ],
    cohort: "2015",
    PhDResearchTitle:
      "Developing Machine Learning Models for Early Disease Detection",
    CARTAGraduate: true,
  },
  {
    id: 18,
    name: { firstname: "Rachel", othername: "", surname: "Lopez" },
    email: "rachel.lopez@example.com",
    sex: "Female",
    currentLevel: "PhD Candidate",
    position: "Teaching Assistant",
    faculty: "Humanities",
    department: "Literature",
    university: "New York University",
    ORCIDNumber: "0000-0018-9012-3456",
    googleScholarProfile: "https://scholar.google.com/rachellopez",
    researchGateProfile: "https://www.researchgate.net/profile/Rachel_Lopez",
    shortBio:
      "Rachel explores contemporary literature and its reflection of societal changes.",
    areaOfSpecialization: ["Contemporary Literature", "Cultural Studies"],
    researchInterest: [
      "Narrative theory",
      "Postmodernism",
      "Digital storytelling",
    ],
    cohort: "2024",
    PhDResearchTitle:
      "The Evolution of Narrative Structures in Digital Literature",
    CARTAGraduate: false,
  },
  {
    id: 19,
    name: { firstname: "Samuel", othername: "", surname: "Miller" },
    email: "samuel.miller@example.com",
    sex: "Male",
    currentLevel: "Postdoctoral Fellow",
    position: "Senior Researcher",
    faculty: "Science",
    department: "Environmental Engineering",
    university: "Duke University",
    ORCIDNumber: "0000-0019-0123-4567",
    googleScholarProfile: "https://scholar.google.com/samuelmiller",
    researchGateProfile: "https://www.researchgate.net/profile/Samuel_Miller",
    shortBio:
      "Samuel is dedicated to developing sustainable water treatment technologies.",
    areaOfSpecialization: ["Water Treatment", "Sustainable Engineering"],
    researchInterest: [
      "Membrane technology",
      "Pollutant removal",
      "Resource recovery",
    ],
    cohort: "2018",
    PhDResearchTitle:
      "Innovative Membrane Technologies for Sustainable Water Treatment",
    CARTAGraduate: true,
  },
  {
    id: 20,
    name: { firstname: "Tina", othername: "", surname: "Clark" },
    email: "tina.clark@example.com",
    sex: "Female",
    currentLevel: "PhD Graduate",
    position: "Lecturer",
    faculty: "Business",
    department: "Finance",
    university: "University of Pennsylvania",
    ORCIDNumber: "0000-0020-1234-5678",
    googleScholarProfile: "https://scholar.google.com/tinaclark",
    researchGateProfile: "https://www.researchgate.net/profile/Tina_Clark",
    shortBio:
      "Tina specializes in financial markets and investment strategies.",
    areaOfSpecialization: ["Financial Markets", "Investment Strategies"],
    researchInterest: [
      "Behavioral finance",
      "Market volatility",
      "Portfolio management",
    ],
    cohort: "2014",
    PhDResearchTitle:
      "Behavioral Biases in Portfolio Management and Their Impact on Market Stability",
    CARTAGraduate: true,
  },
  {
    id: 21,
    name: { firstname: "Uma", othername: "", surname: "Patel" },
    email: "uma.patel@example.com",
    sex: "Female",
    currentLevel: "PhD Candidate",
    position: "Research Assistant",
    faculty: "Science",
    department: "Computer Science",
    university: "University of Illinois Urbana-Champaign",
    ORCIDNumber: "0000-0021-2345-6789",
    googleScholarProfile: "https://scholar.google.com/umapatel",
    researchGateProfile: "https://www.researchgate.net/profile/Uma_Patel",
    shortBio:
      "Uma focuses on artificial intelligence and its applications in autonomous systems.",
    areaOfSpecialization: ["Artificial Intelligence", "Autonomous Systems"],
    researchInterest: [
      "Robotics",
      "Machine perception",
      "Human-AI interaction",
    ],
    cohort: "2025",
    PhDResearchTitle:
      "Enhancing Machine Perception for Autonomous Navigation Systems",
    CARTAGraduate: false,
  },
  {
    id: 22,
    name: { firstname: "Victor", othername: "", surname: "Rodriguez" },
    email: "victor.rodriguez@example.com",
    sex: "Male",
    currentLevel: "Postdoctoral Fellow",
    position: "Research Scientist",
    faculty: "Medicine",
    department: "Genetics",
    university: "University of Michigan",
    ORCIDNumber: "0000-0022-3456-7890",
    googleScholarProfile: "https://scholar.google.com/victorrodriguez",
    researchGateProfile:
      "https://www.researchgate.net/profile/Victor_Rodriguez",
    shortBio:
      "Victor specializes in genetic epidemiology and the study of hereditary diseases.",
    areaOfSpecialization: ["Genetic Epidemiology", "Hereditary Diseases"],
    researchInterest: [
      "Genomic associations",
      "Population genetics",
      "Disease gene mapping",
    ],
    cohort: "2017",
    PhDResearchTitle:
      "Genomic Associations in Hereditary Cardiovascular Diseases",
    CARTAGraduate: true,
  },
  {
    id: 23,
    name: { firstname: "Wendy", othername: "", surname: "Lee" },
    email: "wendy.lee@example.com",
    sex: "Female",
    currentLevel: "PhD Graduate",
    position: "Associate Professor",
    faculty: "Engineering",
    department: "Aerospace Engineering",
    university: "Purdue University",
    ORCIDNumber: "0000-0023-4567-8901",
    googleScholarProfile: "https://scholar.google.com/wendylee",
    researchGateProfile: "https://www.researchgate.net/profile/Wendy_Lee",
    shortBio:
      "Wendy's research focuses on aerospace materials and structural integrity.",
    areaOfSpecialization: ["Aerospace Materials", "Structural Integrity"],
    researchInterest: [
      "Composite materials",
      "Fatigue analysis",
      "Spacecraft design",
    ],
    cohort: "2013",
    PhDResearchTitle:
      "Fatigue Analysis of Composite Materials in Aerospace Applications",
    CARTAGraduate: true,
  },
  {
    id: 24,
    name: { firstname: "Xander", othername: "", surname: "Kim" },
    email: "xander.kim@example.com",
    sex: "Male",
    currentLevel: "PhD Candidate",
    position: "Teaching Assistant",
    faculty: "Science",
    department: "Mathematics",
    university: "University of Chicago",
    ORCIDNumber: "0000-0024-5678-9012",
    googleScholarProfile: "https://scholar.google.com/xanderkim",
    researchGateProfile: "https://www.researchgate.net/profile/Xander_Kim",
    shortBio:
      "Xander specializes in applied mathematics with a focus on computational modeling.",
    areaOfSpecialization: ["Applied Mathematics", "Computational Modeling"],
    researchInterest: [
      "Numerical analysis",
      "Partial differential equations",
      "Simulation techniques",
    ],
    cohort: "2024",
    PhDResearchTitle:
      "Computational Models for Simulating Fluid Dynamics in Complex Systems",
    CARTAGraduate: false,
  },
  {
    id: 25,
    name: { firstname: "Yvonne", othername: "", surname: "Garcia" },
    email: "yvonne.garcia@example.com",
    sex: "Female",
    currentLevel: "Postdoctoral Fellow",
    position: "Senior Researcher",
    faculty: "Medicine",
    department: "Pharmacology",
    university: "University of North Carolina",
    ORCIDNumber: "0000-0025-6789-0123",
    googleScholarProfile: "https://scholar.google.com/yvonnegarcia",
    researchGateProfile: "https://www.researchgate.net/profile/Yvonne_Garcia",
    shortBio:
      "Yvonne researches drug interactions and the development of new pharmacological treatments.",
    areaOfSpecialization: ["Pharmacology", "Drug Development"],
    researchInterest: [
      "Neuropharmacology",
      "Therapeutic agents",
      "Clinical trials",
    ],
    cohort: "2016",
    PhDResearchTitle:
      "Development of Novel Therapeutic Agents for Neurodegenerative Diseases",
    CARTAGraduate: true,
  },
  {
    id: 26,
    name: { firstname: "Zachary", othername: "", surname: "Lopez" },
    email: "zachary.lopez@example.com",
    sex: "Male",
    currentLevel: "PhD Graduate",
    position: "Lecturer",
    faculty: "Humanities",
    department: "Sociology",
    university: "University of California, Los Angeles",
    ORCIDNumber: "0000-0026-7890-1234",
    googleScholarProfile: "https://scholar.google.com/zacharylopez",
    researchGateProfile: "https://www.researchgate.net/profile/Zachary_Lopez",
    shortBio:
      "Zachary studies social behavior and the impact of technology on society.",
    areaOfSpecialization: ["Sociology", "Technology and Society"],
    researchInterest: [
      "Social networks",
      "Digital communities",
      "Behavioral analysis",
    ],
    cohort: "2012",
    PhDResearchTitle:
      "The Impact of Social Media on Community Formation and Social Behavior",
    CARTAGraduate: true,
  },
];
export const institutions = [
  {
    id: 1,
    name: "University of Nairobi",
    location: "Nairobi, Kenya",
    type: "Public",
    website: "https://uonbi.ac.ke",
  },
  {
    id: 2,
    name: "Makerere University",
    location: "Kampala, Uganda",
    type: "Public",
    website: "https://mak.ac.ug",
  },
  {
    id: 3,
    name: "University of Ghana",
    location: "Accra, Ghana",
    type: "Public",
    website: "https://ug.edu.gh",
  },
  {
    id: 4,
    name: "University of Cape Town",
    location: "Cape Town, South Africa",
    type: "Public",
    website: "https://uct.ac.za",
  },
  {
    id: 5,
    name: "University of Ibadan",
    location: "Ibadan, Nigeria",
    type: "Public",
    website: "https://ui.edu.ng",
  },
  {
    id: 6,
    name: "University of Dar es Salaam",
    location: "Dar es Salaam, Tanzania",
    type: "Public",
    website: "https://udsm.ac.tz",
  },
  {
    id: 7,
    name: "Addis Ababa University",
    location: "Addis Ababa, Ethiopia",
    type: "Public",
    website: "https://aau.edu.et",
  },
  {
    id: 8,
    name: "Stellenbosch University",
    location: "Stellenbosch, South Africa",
    type: "Public",
    website: "https://sun.ac.za",
  },
  {
    id: 9,
    name: "University of Zambia",
    location: "Lusaka, Zambia",
    type: "Public",
    website: "https://unza.zm",
  },
  {
    id: 10,
    name: "University of Pretoria",
    location: "Pretoria, South Africa",
    type: "Public",
    website: "https://up.ac.za",
  },
];

export const cohorts = [
  {
    id: 1,
    cohort: 2020,
    description: "Cohort for genetics and molecular biology research.",
  },
  {
    id: 2,
    cohort: 2023,
    description: "Cohort focused on AI and healthcare innovations.",
  },
  {
    id: 3,
    cohort: 2022,
    description: "Cohort for educational psychology advancements.",
  },

  {
    id: 5,
    cohort: 2021,
    description: "Cohort focused on post-colonial African narratives.",
  },
];
